# Generated by Django 5.0.2 on 2024-03-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
